"""Add checkout_request_id to transaction

Revision ID: b97122c5710e
Revises: 0dad8bec90d8
Create Date: 2025-06-26 13:37:03.215533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b97122c5710e'
down_revision: Union[str, Sequence[str], None] = '0dad8bec90d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('checkout_request_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'transaction', ['checkout_request_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='unique')
    op.drop_column('transaction', 'checkout_request_id')
    # ### end Alembic commands ###
