"""add matchmaking queue table and update relationships

Revision ID: f2d798c00968
Revises: b97122c5710e
Create Date: 2025-06-26 13:43:07.814775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2d798c00968'
down_revision: Union[str, Sequence[str], None] = 'b97122c5710e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchmakingqueue', sa.Column('game_type', sa.String(), nullable=False))
    op.add_column('matchmakingqueue', sa.Column('status', sa.String(), nullable=False))
    op.alter_column('matchmakingqueue', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('matchmakingqueue', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_matchmakingqueue_game_type'), 'matchmakingqueue', ['game_type'], unique=False)
    op.create_index(op.f('ix_matchmakingqueue_status'), 'matchmakingqueue', ['status'], unique=False)
    op.drop_column('matchmakingqueue', 'skill_range_min')
    op.drop_column('matchmakingqueue', 'skill_range_max')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchmakingqueue', sa.Column('skill_range_max', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('matchmakingqueue', sa.Column('skill_range_min', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_matchmakingqueue_status'), table_name='matchmakingqueue')
    op.drop_index(op.f('ix_matchmakingqueue_game_type'), table_name='matchmakingqueue')
    op.alter_column('matchmakingqueue', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('matchmakingqueue', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('matchmakingqueue', 'status')
    op.drop_column('matchmakingqueue', 'game_type')
    # ### end Alembic commands ###
