"""Add tournament relations to match

Revision ID: f6368c501241
Revises: f2d798c00968
Create Date: 2025-06-26 13:47:07.069619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6368c501241'
down_revision: Union[str, Sequence[str], None] = 'f2d798c00968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('tournament_id', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('round_number', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'match', 'tournament', ['tournament_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_column('match', 'round_number')
    op.drop_column('match', 'tournament_id')
    # ### end Alembic commands ###
